### ISSUE TITLE
Multiple VL53L0X With atmega2560 using C library 

### ISSUE THREAD

**Issue by Aashutosh3804** [sparkfun/SparkFun_VL53L1X_Arduino_Library#33]
I want to interface 3 VL53L0X TO atmega2560 in arvdude but using c libaraey I can't figure it out can anyone give me code for arv-gcc
Library using
https://github.com/yetifrisstlama/vl53l0x-non-arduino

**Comment by AndyEngland521** [comment]
I am unsure if the VL53L0X has a software configurable address, but the VL53L1X does. In order to utilize it, you will need to hold 2 sensors in reset while you change the address of the third sensor. Then, take one of the sensors out of reset and change it's address as well. This will leave you with three sensors on 3 different I2C addresses. I am closing this issue as it looks like you have posted it in the wrong github repository.
