### ISSUE TITLE
Are you guys in need of the official C API released by ST?

### ISSUE THREAD

**Issue by nrobinson2000** [sparkfun/SparkFun_VL53L1X_Arduino_Library#4]
[It can be downloaded here.](http://www.st.com/content/st_com/en/products/embedded-software/proximity-sensors-software/stsw-img007.html)

It would need to be ported.

**Comment by nrobinson2000** [comment]
Or is forking it and releasing it on GitHub like totally against the software agreement?

**Comment by nseidle** [comment]
Yep. We're very aware of it. We dug quite a bit into the example code and API for the VL53L1X. The problem was porting it to Arduino so that it would compile and be usable as a library. It looks like Pololu [got it to compile](https://github.com/pololu/vl53l1x-st-api-arduino), but they didn't really encapsulate any of the functions to make it easy to use. 

In a perfect world there would be a handful of functions that wrap up the ST API:

* begin
* startMeasurement
* getDistance

And the more advanced functions

* setRange (short, med, long)
* [ROI stuff](https://github.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/issues/3) (that I don't quite understand yet)
* xTalk calibration

The API exposes functions for a lot of these but the documentation is spread across some app notes and the header files.

**Comment by nrobinson2000** [comment]
Thanks @nseidle.

The Pololu library is exactly what I was looking for.

**Comment by nseidle** [comment]
For my own logs: Our lib = 6176 bytes , full ST lib compiled = 20,530 bytes. So depending on how much other things you're doing the SparkFun is a lot lighter weight.
