### ISSUE TITLE
Unable to add library with Arduino IDE 2.0.0-beta.7

### ISSUE THREAD

**Issue by ernestp** [sparkfun/SparkFun_VL53L1X_Arduino_Library#46]
Error: Request installZip failed with message: 2 UNKNOWN: library is not valid: missing header file "SparkFun_VL53L1X_Arduino_Library-master.h"

**Update:**

I was able to add library by unzipping archive, renaming folder to SparkFun_VL53L1X, compressing it as ZIP and then importing new ZIP file.

**Comment by santaimpersonator** [comment]
Unfortunately, we don't provide support for the test (alpha or beta) versions of the Arduino IDE.

I am labeling this as won't fix since it has to do with a beta release of the Arduino IDE. I am also closing this issue; however, feel free to reopen the issue if it is still a problem when the 2.x.x version release.

**Comment by nseidle** [comment]
Just out of curiosity, I tested this with the latest beta and the lib installed without problems. The beta of v2 is still pretty rough but they are getting the edges rounded off. If anyone else still has an issue please let us know. We'll keep an eye on our libs WRT v2 as the beta gets solidified.

![image](https://user-images.githubusercontent.com/117102/131720454-676df233-8121-4c3c-910e-7f5a3babd971.png)
