### ISSUE TITLE
Shouldn't this be x < toSend?

### ISSUE THREAD

**Issue by cpagravel** [sparkfun/SparkFun_VL53L1X_Arduino_Library#6]
I may be misunderstanding the intent, but I believe that using `x < toSend` makes more sense.

https://github.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/blob/a8ac30a671fb6c30367d3c9918ecf23480d0dd3f/src/SparkFun_VL53L1X_Arduino_Library.cpp#L121

**Comment by nseidle** [comment]
Yikes. Yes, that does seem like a bug. I'm not sure how that's working as the limit on the outgoing buffer should be 32 bytes. Hmm. I'll have to take a look.

**Comment by nseidle** [comment]
Looking at what was transmitted with an analyzer, it looks like even with the bug it was limiting to 32 bytes per write. I am guessing that the loop would attempt to write say, 57 bytes (instead of proper 32 max) and the 

    _i2cPort->write(pgm_read_byte_near(configBlock + address + x - 1 - offset));

line would attempt to write 57 bytes but the buffer would cut off the tail end (57-32 = ) 25 bytes. The loop would continue, and re-send the remaining 25 bytes.

![image](https://user-images.githubusercontent.com/117102/40239558-9cd585fa-5a73-11e8-8f73-4ff3047cea61.png)

Good find and thank you for having a look at the library. I've pushed the fix and will release a lib ver shortly.
